### ISSUE TITLE
implement background sounds

### ISSUE THREAD

**Issue by urstruktur** [krachzack/fernspieleditor#2]
It would be cool if one could play background music and control it via the states.
In addition it be awesome if following situation could be modeled:
The user dials a number while audio is being played. The audio pauses and another sound is played (e.g. someone saying "Don't interrupt me!") and then the previous audio file continues.
Thank you for consideration!

**Comment by krachzack** [comment]
Cool feature request!

I suggest we solve this by letting the user select a sound file for each state, containing background music. On state transitions, music continues playing if the target state has the same music, otherwise the target state music starts playing from the beginning.

I think the pause-and-continue aspect you mentioned is relatively unrelated to background music, but I agree that we need this. For that feature, I suggest adding a new checkbox "start over when entering state" to the editor. However, continuation is currently blocked by missing core functionality: [fernspielapparat #5](https://github.com/krachzack/fernspielapparat/issues/5).

**Comment by krachzack** [comment]
In the panel of the right end of the interface, there is now a second tab next to "Inspector", namely "Sounds". Here we can collect sounds and utterances and give them names. Then, for each state, we can select one or more sounds that will be played.
